name: Scala Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: scala-build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0
    - name: Set up Eclipse Temurin - JDK 21
      uses: actions/setup-java@v5.0.0
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Test
      run: sbt test
